### ISSUE TITLE
Choice with single child element

### ISSUE THREAD

**Issue by dixxi** [DLR-LY/CPACS#493] opened 2017-05-22 09:39 UTC
Hi guys!

In the complexContent definition of controlSurfaceSkinCutOutBorderType there is the following structure:
```xml
	<xsd:complexContent>
			<xsd:extension base="complexBaseType">
				<xsd:choice>
					<xsd:sequence>
						<xsd:choice>
							<xsd:sequence>
								...
							</xsd:sequence>
							<xsd:sequence>
								...
							</xsd:sequence>
						</xsd:choice>
					</xsd:sequence>
				</xsd:choice>
			</xsd:extension>
		</xsd:complexContent>
```
The outer choice element has only a single child element. This seems odd to me. Is this intended or can the outer choice be removed? In the CPACS documentation, the outer choice element is not listed.

Thank you!

**Comment by ArneBachmann** [comment] 2017-05-22 11:44
Duplicate of #474

**Closed** 2017-06-13 08:42 UTC
